
services:

  test_hh_127062965_booking:
    container_name: test_hh_127062965_booking
    restart: always
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - '${BACKEND_PORT:-5004}:5000'
      - '${DEBUG_BACKEND_PORT:-9229}:9229'
    environment:
      - NODE_ENV=${APP_ENV}
    networks:
      - test_hh_net_127062965
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5004/api"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s


networks:
  test_hh_net_127062965:
    external: true
